artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view
  local_data_file: artifacts/data_ingestion/Kidney-CTScan-data.zip
  unzip_dir: artifacts/data_ingestion